<?php

function lorem($ln){
$L="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec nisi at massa accumsan elementum dignissim vel magna. Etiam odio mi, gravida eu tellus vel, congue finibus sapien. Donec vel dolor viverra, ullamcorper eros a, egestas mauris. Sed eget quam vitae libero faucibus tristique. Donec accumsan nunc eget ipsum rutrum scelerisque. In hac habitasse platea dictumst. Curabitur posuere, elit id consequat dignissim, tellus dui gravida mauris, vel aliquam magna diam vitae felis. Proin et dignissim quam, ut gravida purus. Ut ac leo in felis tincidunt ornare ut mollis orci.

Phasellus aliquet faucibus nunc, non gravida erat. Mauris posuere nisl eget massa imperdiet, eget commodo nibh congue. Proin mattis molestie quam. Vivamus bibendum interdum sem in accumsan. Vivamus feugiat odio sit amet ipsum condimentum viverra. Fusce eget ipsum sed orci suscipit vehicula. Nunc vehicula dui a lacus lacinia rutrum. In eu lobortis dui. Duis porta purus eu velit pharetra commodo.

In at neque diam. Quisque eget erat in tortor laoreet laoreet vitae non tortor. Pellentesque quis placerat nibh, ac venenatis eros. Aliquam tellus mi, viverra sed semper non, volutpat sagittis sapien. Nulla finibus finibus leo non fringilla. Duis vitae enim nisl. Vestibulum eget porta metus. Suspendisse non semper nunc, quis feugiat libero. Aenean et mauris quis tellus auctor hendrerit. Sed nec tellus orci. Donec ullamcorper quis ante at tristique. Nam ornare fringilla mattis. Integer faucibus ullamcorper neque sit amet facilisis. Nulla sed leo nulla.

Sed ac condimentum nibh. Maecenas vulputate orci non diam interdum tincidunt. Phasellus non ligula a sapien efficitur pretium. Nullam vitae arcu fringilla tellus aliquet tincidunt. Donec sagittis magna ullamcorper augue consequat, sit amet mattis leo sodales. Aenean imperdiet lectus metus, nec venenatis sapien eleifend ac. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse hendrerit eu lorem id fermentum. Ut non metus vel sapien gravida consequat. Donec viverra, magna ac finibus hendrerit, ligula leo mattis neque, ac hendrerit orci lorem a mauris.

Etiam elit sapien, interdum sit amet imperdiet sit amet, vestibulum at nulla. In dignissim sit amet libero eget sodales. Donec ultricies magna urna, nec vulputate mi tempus eleifend. Nullam consequat, arcu vel elementum pretium, turpis justo lacinia nulla, non dapibus est mi et lectus. Vivamus efficitur mauris orci, vitae tempus leo ultricies et. Integer non aliquet lorem. Fusce iaculis vulputate purus, nec cursus augue ultricies at. Curabitur efficitur egestas tincidunt. Mauris commodo bibendum elit ac porta.

Quisque sed rhoncus urna. Nunc placerat sollicitudin sapien nec sagittis. In eget mattis ante. Aliquam ut tortor pellentesque, bibendum elit sed, placerat est. Vivamus egestas risus id fringilla efficitur. Nulla quis metus quis nisl volutpat sodales. Phasellus bibendum tortor ex, sed placerat velit porta consectetur. Quisque faucibus lorem massa, id tempor ex varius sed. In libero tortor, posuere vel malesuada vitae, interdum eu felis. Aenean interdum feugiat venenatis.

Suspendisse potenti. Phasellus dui magna, gravida vitae arcu a, posuere elementum urna. Quisque dignissim magna et nisl congue convallis. Integer nec nulla ut lorem elementum vulputate a nec tortor. Phasellus ornare lorem vitae eros porttitor, in pellentesque dolor aliquet. Vivamus at sodales nisl. Morbi porttitor, nisi finibus tincidunt hendrerit, ex ante fringilla velit, sed viverra mi turpis eu lorem. Donec tristique, orci ut elementum vestibulum, sem sapien feugiat nisl, tempus hendrerit elit metus eu lectus. Pellentesque efficitur enim sit amet nunc iaculis, at consectetur odio molestie. Etiam vulputate nulla eget ipsum vulputate imperdiet. Mauris id odio eget magna elementum finibus. Donec condimentum nec neque ac egestas. Fusce in velit mauris.

Curabitur lobortis, ipsum vel auctor sollicitudin, felis arcu accumsan eros, dictum fermentum ante tortor eu risus. Cras interdum sem non cursus congue. Etiam blandit orci sed quam facilisis, ac bibendum purus porta. Praesent ut eros arcu. Nullam ante justo, blandit eu venenatis eget, cursus nec libero. Nunc eget mollis eros, sed porttitor justo. Aliquam venenatis urna ex, non sollicitudin felis rhoncus et. Integer in luctus nibh. Pellentesque dolor erat, dignissim sit amet semper pretium, molestie in magna. Sed scelerisque et odio scelerisque tristique.

Nunc eros metus, ornare in mollis a, fermentum ut nulla. Aenean rutrum eleifend mollis. Nulla suscipit elementum lacus, at feugiat mi tempus nec. Fusce pharetra leo at condimentum mollis. Mauris fringilla lectus at mauris vehicula, ac sagittis ligula vulputate. Nullam blandit tempor mauris ut tempus. Phasellus imperdiet iaculis elit, id facilisis lectus imperdiet semper. Curabitur eu nunc sit amet ligula sollicitudin sodales et ut augue.

Sed tincidunt erat quis pretium posuere. Cras ultrices dolor non neque porta ornare. Donec ut condimentum quam. Quisque ac nisl tristique, dignissim est non, tincidunt velit. Etiam sed massa vitae dolor semper tristique. Pellentesque gravida tempor enim at ullamcorper. Aenean elementum augue ac enim ullamcorper, vel interdum felis faucibus. Phasellus ultricies nulla at lorem gravida elementum. Duis sodales nibh et justo congue, a elementum urna tincidunt. Etiam id mauris arcu.

Morbi vulputate faucibus ex, quis posuere massa venenatis nec. Aliquam auctor lobortis nulla, ut pulvinar ante aliquet quis. In vitae fermentum dui. Praesent eu nisi suscipit, interdum risus id, posuere nulla. Nullam vel quam non erat maximus cursus. Sed convallis enim sit amet tortor dignissim finibus. Suspendisse mauris felis, auctor aliquam posuere in, tempor vitae risus. Cras vestibulum urna non magna accumsan tempor. Ut vel commodo ante, at elementum justo. Nullam quis fringilla mi. Proin vitae nunc quam. Curabitur dapibus diam nec velit sollicitudin, at volutpat nunc egestas. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Duis in urna dui. In eget ante eros. Pellentesque imperdiet aliquam urna, non pellentesque nisl vulputate non. Cras hendrerit, justo nec vulputate euismod, urna orci sagittis dolor, vitae accumsan urna neque in arcu. Aenean sit amet metus ut metus ultricies scelerisque. Nullam ornare, lorem vel tempor eleifend, dolor velit tempus turpis, et gravida magna lorem ut urna. Morbi eleifend odio suscipit fringilla aliquet. Vivamus sit amet imperdiet lorem, non ultrices massa. Vestibulum iaculis mauris non tempus tempor. Aenean eget lectus vel leo placerat laoreet. Praesent rhoncus, arcu sit amet fringilla congue, purus quam placerat velit, nec condimentum augue erat vel nibh.

Vivamus eget luctus nibh. Etiam venenatis vel dolor a porttitor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed eget eros mauris. Nunc ornare diam dolor, eu rutrum nulla varius eu. In nec tempus lectus, eget eleifend urna. Donec non sagittis sapien. Donec magna magna, porta vel odio quis, cursus volutpat orci. Maecenas condimentum viverra nulla lobortis aliquam. Donec viverra eleifend mi non consequat. Curabitur pretium libero enim, dapibus faucibus tellus iaculis sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi luctus lorem consequat nunc finibus, vitae dignissim est tempus. Aliquam pretium ante sit amet augue blandit, id gravida ipsum tempus. Donec tincidunt eros ligula. Vivamus dapibus sapien ut leo bibendum porta.

Suspendisse auctor nulla mauris, vitae ultricies neque varius eget. Etiam diam orci, porttitor at nisl sed, imperdiet gravida tortor. Praesent nisi ante, luctus id nunc vel, convallis venenatis elit. Sed viverra nec sapien vestibulum consequat. Phasellus sed nisi vitae ex imperdiet ultricies nec vitae erat. Cras rutrum massa massa, quis sollicitudin lectus ornare eu. Aliquam eu nibh et est vestibulum fermentum. Maecenas dolor est, gravida ut sem non, bibendum tincidunt tellus.

Fusce id scelerisque justo. Donec laoreet ex nec metus sagittis, non mollis mauris tristique. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum aliquam tempus consequat. Donec sodales sollicitudin quam, vitae vehicula magna aliquet vitae. Duis mollis arcu id purus hendrerit, ac porta tortor interdum. Sed iaculis, odio in consequat hendrerit, nisi lacus pulvinar sem, a cursus odio massa nec orci. Praesent a bibendum nisl. Phasellus mollis tincidunt bibendum. Sed blandit urna a aliquet fermentum. Nam aliquam ultricies est, eu vulputate nulla mattis a. Vestibulum vehicula justo id enim mollis, sed ornare enim finibus. Morbi ut luctus purus. Duis pretium in ex eget porta. Aliquam lacus nisl, porta at sem vel, aliquam lacinia arcu.

Sed ipsum magna, aliquam quis dapibus in, facilisis maximus sapien. Quisque condimentum erat in ex ultrices, vitae eleifend augue eleifend. Integer mollis condimentum molestie. In hac habitasse platea dictumst. Nulla nisl ante, faucibus sit amet faucibus in, vehicula a magna. Integer imperdiet quam sit amet aliquam feugiat. Vivamus faucibus sed massa at ultricies. In in congue dui, ac ornare metus. In id ante imperdiet, sodales risus a, tempus elit. Sed sed diam rhoncus, placerat massa eget, laoreet risus. Ut ullamcorper pellentesque ornare. Integer a lorem accumsan, venenatis ligula sed, dignissim libero. Duis viverra, mauris at auctor dictum, nibh nibh mollis quam, quis tempor turpis nibh ac sapien. Vestibulum orci ante, tincidunt in sodales quis, venenatis id nisi.

Praesent volutpat sodales nisi, non semper quam sagittis vitae. Nunc nec vehicula neque. Vestibulum commodo tortor nec feugiat laoreet. Duis eros dolor, tempor eget fringilla ac, porttitor placerat sapien. Aliquam consectetur eleifend mauris, eu facilisis nisl ullamcorper eget. Quisque vel vestibulum mauris, ac dictum justo. Pellentesque et elit at arcu volutpat hendrerit at eu quam. Praesent nisl leo, varius non est sit amet, posuere pellentesque felis. Nunc quis luctus ligula. Duis in ipsum et nibh finibus mattis. Aenean sed ante ut turpis elementum tincidunt. Etiam eget aliquet purus. Nullam mi nisi, malesuada pharetra sodales ut, facilisis vel diam.

Nunc id tellus sed ipsum blandit tincidunt. Phasellus rhoncus arcu ultrices turpis scelerisque, ut euismod orci pellentesque. Aliquam at ex et urna vestibulum aliquam in a mi. Donec lacus leo, placerat ut varius ut, finibus scelerisque nulla. In mattis sollicitudin leo, at pulvinar risus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed quis ipsum volutpat diam mattis dignissim sed eu elit. Aliquam ligula arcu, auctor eget enim non, porttitor accumsan quam. Fusce sit amet nibh vitae sapien cursus luctus. Mauris facilisis id lectus et dignissim. Nunc sapien libero, pellentesque ac ligula sit amet, accumsan lobortis eros. Quisque eget pellentesque dolor. Aenean pellentesque sed leo sed consequat. Pellentesque scelerisque quam ut lacus ornare, ut suscipit elit feugiat. Nullam hendrerit justo vel ex eleifend sollicitudin. Vivamus facilisis semper massa eu facilisis.

In laoreet varius dolor, in maximus est pulvinar euismod. Phasellus tempus eros mi, eu suscipit orci pretium eget. Phasellus vitae dui consectetur, auctor eros at, ultricies dui. Morbi ultricies elit nec nibh rutrum, nec consequat metus porttitor. Aenean facilisis sed massa ac hendrerit. Donec sit amet ipsum ac nibh sollicitudin finibus. Nam dictum sit amet magna vel condimentum. Morbi sodales felis ac scelerisque bibendum. Ut sed lacus mollis, semper ligula eget, bibendum erat. Morbi consequat scelerisque tincidunt. Praesent pellentesque tincidunt eleifend. Phasellus sit amet felis eleifend, fringilla orci eu, vulputate tellus. Aenean eu nisl in arcu tincidunt vestibulum. Sed porttitor eget ipsum vitae congue.

Sed laoreet justo eu est tempor ultrices. Praesent sed gravida purus, in eleifend lacus. Vestibulum nec nisl eu nibh euismod luctus. Donec sed lorem convallis, auctor arcu eget, dignissim erat. Duis fermentum tincidunt lacinia. Suspendisse quis consectetur orci. Praesent tincidunt turpis eget ex vehicula, in tempor sapien pellentesque. Pellentesque imperdiet vel velit vitae pulvinar. Integer condimentum tellus quis enim accumsan tempus. Nulla et imperdiet risus.

Cras sed urna nulla. Etiam pellentesque non justo id pharetra. In ac malesuada dolor, sed bibendum dui. Ut dignissim nisi vel ex maximus, quis consequat nulla pretium. Fusce egestas blandit pharetra. Cras velit ante, bibendum sed varius quis, porta et tortor. Pellentesque convallis elit odio, eget malesuada est dapibus luctus. Integer sagittis facilisis quam ut accumsan. Integer dignissim erat ut cursus consectetur. Pellentesque ac dui sit amet enim mattis sollicitudin ut sed lectus. Nam fermentum tortor vel justo vehicula laoreet. Proin in sem arcu. Quisque aliquet luctus ex vel semper. Nullam eget est cursus, feugiat est vel, efficitur enim.

Maecenas sollicitudin interdum felis fringilla condimentum. Morbi placerat finibus arcu sed vehicula. In ullamcorper a nulla eu sodales. Vestibulum congue turpis id elementum tempus. Suspendisse dignissim aliquam dictum. Etiam ultricies est scelerisque urna ultricies ullamcorper. Aenean non erat eu tortor pellentesque mollis. Vestibulum tristique a urna in consectetur. Nulla viverra egestas neque, vel auctor ante efficitur et. Nullam venenatis est at mattis pretium. Nullam justo ligula, mattis ac lacus at, elementum tincidunt nibh. Sed vel bibendum ante. Quisque in nibh eget urna ultrices rhoncus id vel augue. In hac habitasse platea dictumst. Vivamus vestibulum rutrum ipsum, sit amet aliquet ante hendrerit a. Donec id metus non tellus pellentesque pulvinar.

Sed hendrerit urna ut ante gravida, vitae aliquam nisl pretium. Ut in massa finibus, venenatis odio a, posuere nisl. Proin eu auctor mi, eu pretium lacus. Quisque id posuere metus. Integer blandit leo vitae interdum laoreet. Proin accumsan ipsum non efficitur eleifend. Fusce venenatis neque gravida convallis sollicitudin. Vestibulum finibus dui sit amet justo sagittis efficitur. Nulla at massa eget tortor ullamcorper lacinia.

Nulla imperdiet fringilla mi a rhoncus. Morbi et nisi nunc. Quisque elementum nisl a ipsum posuere, sed laoreet sapien interdum. Vivamus eget enim sodales, lacinia orci vitae, ultricies risus. Suspendisse nec posuere nisl. Nunc rhoncus mi eget eros tincidunt lobortis. Quisque sem quam, vulputate quis ligula vel, imperdiet dignissim libero. Integer luctus porttitor maximus. Morbi non bibendum nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec quis dui posuere, molestie lectus condimentum, volutpat orci. In sit amet imperdiet magna. Vestibulum pellentesque eget urna sed aliquet. Aliquam dictum suscipit turpis ac dapibus. Nullam auctor fermentum ipsum quis mattis.

Donec ligula quam, aliquet vel ullamcorper in, posuere vitae mauris. Aenean laoreet molestie molestie. Aliquam erat volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam blandit tempus ex at congue. Duis ultricies ornare nibh ac tristique. Donec consequat sed metus at hendrerit. Morbi a erat purus. Phasellus ut consectetur lorem, ut facilisis risus.

Aliquam in lectus feugiat, finibus nunc sed, dignissim sem. Aenean hendrerit bibendum lorem, eu venenatis velit malesuada eget. Donec fringilla ex urna, ut fringilla lorem fringilla sit amet. Morbi vitae aliquam dolor, sit amet lacinia massa. Sed facilisis dolor eget nibh consectetur faucibus. Vivamus vel leo turpis. Nulla facilisi. Donec venenatis, ante vel aliquam iaculis, velit diam ornare dui, eu vulputate ex justo quis mauris. In sodales vitae est sit amet viverra.

Nullam dapibus justo quis elementum facilisis. Pellentesque iaculis id justo in fringilla. Nullam vel velit in metus congue imperdiet quis eu elit. Duis euismod at metus non interdum. Vivamus quis dolor ac augue congue imperdiet congue in sem. Proin euismod velit id eros pellentesque, quis porta ex laoreet. Suspendisse ut posuere quam, eget sodales leo. Aenean ante odio, aliquet ac tortor eget, ultrices venenatis lorem. Pellentesque a sapien egestas ante rutrum iaculis. Morbi a auctor justo. Ut laoreet magna eu leo ultricies, a tempus lectus aliquam. Nam eu sem ut odio accumsan maximus vitae at ante. Etiam sollicitudin, nibh a placerat dictum, nisi mi porttitor lectus, et bibendum ex tellus at dolor.

Maecenas condimentum ligula at nisl malesuada elementum. Sed et fermentum quam, id volutpat libero. Suspendisse suscipit nunc eu metus accumsan mattis. In fringilla lectus in augue consequat vestibulum. Aenean pretium mollis risus nec lacinia. Donec pellentesque, ipsum a mollis hendrerit, dui urna vestibulum odio, sed efficitur augue turpis non arcu. Nulla ligula metus, varius at augue et, bibendum facilisis lacus. Etiam orci leo, fermentum sit amet cursus at, dapibus ut eros. Pellentesque non pulvinar mauris. Cras nec magna facilisis diam varius hendrerit. Phasellus commodo, ipsum non pellentesque posuere, nisl enim ornare eros, et accumsan lacus odio in augue. Phasellus vulputate, mi eget congue mollis, eros elit malesuada ante, scelerisque pulvinar sem massa non nunc.

Fusce suscipit leo non odio sodales imperdiet sit amet ut sem. Proin et diam vitae metus maximus ultrices vel quis purus. In sed laoreet ipsum. Pellentesque et lectus tristique nunc tempor feugiat. Proin aliquet ante sem. Proin consequat eleifend interdum. Praesent ac congue dolor, id faucibus magna. Morbi posuere dictum quam et finibus. Pellentesque non aliquam tellus.

Etiam rhoncus felis sapien, ut porta erat consectetur volutpat. Cras sit amet mattis quam, vel convallis lacus. Sed ullamcorper, purus pharetra pulvinar viverra, tortor metus condimentum ipsum, eget dignissim felis mauris quis mauris. Sed convallis ornare diam, non facilisis tortor lacinia eget. Etiam sodales, nunc id cursus scelerisque, orci metus rutrum felis, nec bibendum nunc nulla sed nulla. Integer accumsan luctus ante. Mauris iaculis sagittis est mattis dictum. Morbi eleifend, enim sit amet hendrerit facilisis, sapien ante condimentum quam, sit amet volutpat metus odio pulvinar risus. Donec orci felis, efficitur non elit vel, dignissim lacinia arcu. Ut felis sapien, scelerisque nec scelerisque ac, ullamcorper vel sem.

Donec pellentesque enim non neque varius, at sollicitudin risus scelerisque. Duis id nibh tempor, laoreet est non, luctus augue. Nulla id elit eget nisl sagittis feugiat feugiat et magna. Nulla cursus facilisis nunc sodales pellentesque. Fusce nec neque quis sapien congue dignissim in consectetur diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque facilisis, augue in vehicula commodo, libero leo rutrum leo, mattis vehicula sem sapien et purus. Nulla interdum nibh quam, ut feugiat ipsum pellentesque nec. Ut in egestas leo.

Cras interdum consequat aliquam. Fusce interdum commodo nulla at dapibus. Sed vulputate dui dictum iaculis rutrum. Fusce a commodo mi, ac blandit est. Curabitur eget nisi quis felis pharetra volutpat. Donec venenatis massa id nibh fermentum scelerisque. Maecenas at neque porta, volutpat nisl eget, maximus tortor. Integer luctus viverra rhoncus. Phasellus euismod lacus eget cursus consequat. Quisque efficitur hendrerit nisi, in rutrum tortor iaculis vitae. Nulla pharetra felis quis libero tincidunt scelerisque. Curabitur venenatis maximus aliquet. Ut quam ipsum, imperdiet ac varius non, viverra eu justo. Pellentesque malesuada at diam vel ultricies.

In pellentesque pretium purus at placerat. Donec id tortor at nisi rutrum malesuada. Morbi metus elit, cursus quis ullamcorper at, viverra id lorem. Ut sed aliquet nisi, ut egestas neque. Ut eu fringilla risus. Phasellus nec enim tempor, viverra leo ac, pharetra turpis. Etiam eleifend quam nec diam mattis vestibulum. Duis scelerisque vel libero eget fringilla. Donec cursus odio metus, et convallis nulla ultricies suscipit. Fusce et tristique metus. Quisque ac arcu et turpis dapibus lobortis.

Maecenas fringilla condimentum sapien quis pretium. Vivamus a convallis dolor, vitae porttitor tortor. Nunc iaculis purus non elementum porta. Duis rutrum bibendum augue a facilisis. Mauris elementum quam id magna faucibus aliquam. Aliquam leo odio, dictum lacinia lacinia bibendum, ullamcorper at eros. Aenean volutpat neque ac accumsan pharetra. Quisque sit amet arcu vel eros luctus venenatis ac ut diam. Quisque ut erat non lacus pharetra aliquam sed sed mauris. Suspendisse potenti. Sed egestas id dolor ac luctus. Nulla vehicula ex quis nisi molestie, nec eleifend augue venenatis.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sit amet sem ac nibh posuere pulvinar. Proin faucibus dolor vitae nisl posuere pulvinar. Nam massa lacus, facilisis eget nisi eu, dignissim tempor turpis. Aliquam efficitur mauris nisi, vel molestie lorem ornare condimentum. Cras sollicitudin mattis magna eleifend commodo. Praesent nunc dui, dignissim a mauris at, blandit aliquam odio. Nullam accumsan turpis et nisl tempor ultrices. Sed convallis mi ut dapibus commodo. Nullam tempor nunc vitae pellentesque rhoncus. Fusce nunc ante, gravida vitae sem ut, porta aliquam massa. Praesent sagittis ante vitae fermentum malesuada. Nullam sed pretium nunc. Suspendisse vitae erat placerat, ultricies erat dictum, suscipit neque. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Cras ut urna ipsum. Vestibulum mi sapien, gravida sit amet euismod vitae, ornare ut massa. Aenean imperdiet, quam sed ultrices pretium, arcu justo suscipit mauris, eget pretium diam sem sit amet elit. Sed risus magna, porta sit amet elit in, suscipit laoreet neque. Praesent consectetur, orci id vulputate scelerisque, sem sapien varius leo, quis fringilla ex enim sit amet nisi. Sed ac neque ac nisl congue suscipit eu eget tortor. Vestibulum in lacus elementum, rutrum lorem eu, dapibus massa. Pellentesque congue neque non efficitur dictum. Fusce sit amet pharetra mi. Nulla lacinia quam ut egestas dapibus. Mauris nec urna quis neque tempor mollis. In orci sapien, tincidunt id lorem vitae, luctus rhoncus arcu.

Fusce quis tellus enim. Duis vitae dapibus ex. Mauris sollicitudin tortor libero, vitae dictum turpis egestas eu. Aliquam nulla arcu, pretium eget dignissim eu, consectetur ut nibh. Aliquam eu arcu gravida, scelerisque nulla sit amet, malesuada purus. Vestibulum tortor neque, pretium sed viverra vitae, dapibus nec magna. Suspendisse auctor nisi ac dapibus interdum. Sed malesuada, lacus ut ornare cursus, neque urna malesuada diam, id dignissim enim lectus quis magna. Nunc feugiat, lacus id congue tincidunt, magna massa lobortis mauris, et aliquam eros felis ac est. Proin vitae mi nunc. Integer ac elit tortor. Sed congue nunc turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam erat volutpat.

Cras malesuada arcu eu mauris maximus, quis pulvinar dolor fringilla. Morbi velit nunc, venenatis eget augue id, cursus vulputate ex. Phasellus vitae leo quis felis dapibus porttitor nec id augue. Phasellus lacinia molestie scelerisque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed consequat dignissim luctus. Praesent sodales consequat velit quis iaculis. Pellentesque ornare eros in tincidunt tristique. Nunc sit amet ultricies arcu, nec egestas dolor. Mauris dignissim nunc quam, in pellentesque elit bibendum cursus. Sed in magna sit amet tellus ultricies vestibulum fringilla et ante.

Nullam rhoncus lorem nisl, ut pharetra mi consequat id. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer sit amet massa accumsan, mattis justo ac, viverra neque. Aliquam erat volutpat. Nunc in ante dui. Etiam arcu elit, bibendum sed suscipit et, tempus at odio. In cursus odio nec elit hendrerit condimentum. Nulla facilisi. Integer dapibus, neque a varius molestie, metus diam auctor orci, id condimentum neque tortor ut nunc. Nam eget blandit ante. Vivamus ut orci in quam porta tristique. Suspendisse sit amet mi maximus, molestie lacus vestibulum, finibus leo. Cras eu condimentum quam, et aliquet purus. Aliquam pretium sed justo at hendrerit.

Nunc convallis arcu ut velit sodales suscipit. Duis id ex pharetra, mattis est a, tincidunt orci. Nullam nec lectus eros. Curabitur placerat ante nibh, eget convallis libero gravida nec. Fusce turpis lectus, fringilla sed scelerisque sed, rutrum a lorem. Vivamus efficitur eget erat nec dapibus. Vivamus euismod, quam a euismod tincidunt, sem lacus ultrices tellus, ut venenatis tortor sapien nec nibh. Curabitur ullamcorper leo eget odio elementum, sit amet tincidunt elit sodales.

Etiam et lacus accumsan, dapibus ex eget, egestas lectus. Fusce vestibulum ex nec tortor laoreet, non eleifend sem semper. Curabitur lobortis, velit et imperdiet condimentum, leo diam dignissim nulla, nec ornare elit nibh faucibus sem. Fusce massa ex, posuere vitae diam ac, pulvinar accumsan urna. In ut risus tellus. Donec posuere ligula dolor, aliquam ultricies enim pharetra sit amet. Donec posuere dui et tristique sollicitudin.

Quisque fermentum fermentum ante, nec pharetra neque. Aliquam non sapien vel sapien malesuada feugiat ut vitae eros. Morbi accumsan varius tortor nec varius. Aliquam semper, elit in vestibulum iaculis, quam arcu porta erat, sed elementum elit felis vitae ligula. Donec leo lacus, dignissim et vehicula vitae, molestie sed velit. Vivamus dictum dictum elit, in accumsan arcu varius vitae. Curabitur et odio eu quam ullamcorper tincidunt. Nunc sodales diam et laoreet suscipit. Sed eu metus at ligula ullamcorper sagittis. Praesent elementum ac lacus sit amet gravida. Sed porttitor tortor non tempus rhoncus. Integer vehicula neque ante, in dapibus est dignissim ac. Sed lobortis mi placerat imperdiet vestibulum. Nullam at lectus velit. Vivamus tincidunt vel quam consectetur fermentum. Donec vitae rutrum risus, quis aliquet lacus.

Duis a nisi dignissim, volutpat purus eu, gravida dolor. Nullam sed sodales quam. Suspendisse pellentesque cursus nisi. Sed consequat venenatis laoreet. Mauris scelerisque bibendum nisl commodo pretium. Mauris eget ultricies diam. Aliquam rutrum volutpat sagittis. Etiam enim mauris, facilisis a massa non, lobortis aliquet risus. Nulla interdum in velit sit amet aliquet. Aliquam finibus auctor turpis eu venenatis. Etiam vulputate nisi non sagittis pulvinar. Integer facilisis massa ipsum, malesuada scelerisque felis euismod vel. Nunc odio dui, fringilla at felis in, laoreet tristique arcu. In in eleifend enim, eu congue orci. Ut tempor quis mi a molestie.

Pellentesque sit amet placerat neque, non eleifend tortor. Cras tellus elit, volutpat et vehicula et, facilisis eu nunc. Vestibulum dui nisl, elementum eu nibh nec, pharetra consectetur dolor. Nulla maximus mauris leo, vel volutpat lacus commodo ac. Nam vitae est non ligula consectetur pellentesque sed vel purus. Nullam eget convallis ante. Fusce et cursus justo, at cursus odio. Quisque eu mollis purus. Duis malesuada fermentum iaculis. Nulla non lobortis ex. Pellentesque lacinia purus nec lacinia rhoncus.

Suspendisse vel eros sed risus consequat dapibus. Etiam non nibh arcu. Donec non felis a magna iaculis iaculis. Nullam gravida orci vel sapien venenatis posuere. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tristique mauris venenatis justo venenatis ultrices. Nulla suscipit purus commodo tortor fringilla aliquet. Proin id dui risus.

Nullam malesuada vulputate felis sit amet dictum. Integer ut condimentum tortor. Suspendisse vitae tellus iaculis, gravida nisl at, convallis erat. Morbi vel efficitur nisl. Proin laoreet dictum erat, id sagittis quam pulvinar a. Praesent quis velit cursus, dignissim neque ut, volutpat ante. In molestie justo eu dapibus sagittis. Suspendisse iaculis lacus rhoncus, tristique dolor id, convallis turpis. In libero massa, tincidunt ac rutrum at, elementum at nisl. Sed sit amet felis eu erat malesuada lobortis et at augue.

Mauris interdum vehicula tortor et sollicitudin. Duis sed purus vitae lectus condimentum scelerisque. Sed rhoncus vel ex nec convallis. Cras facilisis, enim a venenatis pulvinar, enim lectus facilisis purus, at ultrices sapien enim in lacus. Vivamus eleifend eu purus a aliquet. Nam id nunc euismod, feugiat sapien nec, semper metus. Suspendisse potenti. Fusce eget sagittis risus.

Sed vulputate urna et elementum mollis. Fusce sit amet semper lacus. Suspendisse rutrum dui vel finibus feugiat. Sed quis semper libero, quis cursus ex. Integer dolor augue, ullamcorper vel sodales at, consectetur id sem. Curabitur vel quam vel tortor placerat finibus nec in odio. Curabitur interdum, tellus quis hendrerit suscipit, diam magna malesuada est, at condimentum massa mi sit amet quam. Aenean aliquet, ipsum in sodales malesuada, justo purus facilisis eros, in mattis erat metus eu diam. Maecenas fringilla ante elit, a sagittis dui vulputate eget. Nullam interdum ante interdum lobortis accumsan. Duis augue augue, imperdiet ac eleifend eget, lacinia sed lectus. Nam rutrum sapien ante, nec dapibus ante tempus quis. Nullam et euismod massa. Morbi commodo pharetra euismod. In leo lorem, mattis in dapibus non, accumsan at mi.

Donec quis tincidunt nibh, et sollicitudin magna. Praesent eget feugiat odio. Vivamus eu commodo odio, et interdum neque. In laoreet ex augue, vel rutrum nisl dapibus ac. Nullam ut lectus quis neque interdum rhoncus ut vel sem. Proin tincidunt auctor sagittis. In ac est vitae sem dignissim rhoncus a et diam. Etiam tempus facilisis luctus. Suspendisse ultricies volutpat sem vel lacinia. Nulla facilisi. Donec et turpis nisi. Vestibulum molestie mi nec consectetur laoreet.

Mauris ultricies scelerisque odio, non ullamcorper orci. Duis quis neque erat. Cras finibus magna eu ligula tristique, quis aliquet odio ultricies. Proin at tincidunt sapien. Proin luctus lacus semper sapien sodales auctor sed vel orci. Aenean elementum massa ornare gravida dignissim. Curabitur accumsan lorem vitae purus euismod facilisis. Fusce posuere ante quis posuere ultricies. Sed tempus nunc ac nisl vehicula, at vestibulum dui commodo. Donec ultricies purus sit amet viverra rhoncus. Donec nulla metus, lacinia at cursus eget, efficitur sit amet lacus. In hac habitasse platea dictumst. Praesent interdum suscipit elit, a vestibulum urna imperdiet et. Donec gravida, ex in maximus accumsan, elit lacus aliquam risus, id fermentum leo lectus sed ligula. Suspendisse posuere ac elit vel lobortis. Vivamus molestie lorem non nunc consequat vehicula.";




	echo(substr($L,rand(1,strlen($L)-$ln),$ln));
}

?>